source :gemcutter

gem "nokogiri"
gem "async-rack"
gem "ezcrypto"
gem "sinatra"
gem "async_sinatra"
gem "typhoeus"
gem "sinatra_more"
gem "warden"
gem "ruby-debug19"
gem "rack-flash"
gem "data_mapper", "1.0.0.rc3"
gem "dm-postgres-adapter", "1.0.0.rc3"
gem "haml"